### ISSUE TITLE
GPT-4 AMR-LDA实验代码没有

### ISSUE THREAD

**Issue by liqinga** [Strong-AI-Lab/Logical-Equivalence-driven-AMR-Data-Augmentation-for-Representation-Learning#1]
您好，
在项目代码中我没找到GPT-4 AMR-LDA的实验代码，请问是不公开么？

**Comment by 14H034160212** [comment]
您好，目前文章还在投稿中，会后续整理好代码开放出来，谢谢关注

**Comment by 14H034160212** [comment]
您好，我们关于GPT-4 prompt aumgentation的方法在下面的链接

https://github.com/Strong-AI-Lab/Logical-Equivalence-driven-AMR-Data-Augmentation-for-Representation-Learning/blob/main/logical_equivalence_functions.py

构造好的数据按照下面的格式整理到GPT-4可以读取的格式并进行测试

https://github.com/Strong-AI-Lab/Logical-and-abstract-reasoning
